/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.aluguel.ferramentasaluguel.view;

import br.com.aluguel.ferramentasaluguel.dao.ClienteDAO;
import br.com.aluguel.ferramentasaluguel.model.Clientes;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danie
 */
public class telaListaClientes extends javax.swing.JFrame {

    
     public static telaListaClientes instanciaAtual;
    /**
     * 
     * Creates new form telaListaClientes
     */
    public telaListaClientes() {
        instanciaAtual = this;
        initComponents();
        setLocationRelativeTo(null);
        ClienteDAO dao = new ClienteDAO();
        List<Clientes> clientes = dao.listar("");
        preencherTabela(clientes);
        
    }
    
    /**
     * Função que preencher a tabela com as informações 
     */
    
  
    
 public void preencherTabela(List<Clientes> clientes) {
     String colunas[] = {"ID","Nome", "CPF", "Celular", "E-mail"};
     String dados[][] =new String[clientes.size()][colunas.length];
     
     int i = 0;
     
     for(Clientes c : clientes) {
         dados[i] = new String[] {
             String.valueOf(c.getId()),
             c.getNome(),
             c.getCpf(),
             String.valueOf(c.getCelular()),
             c.getEmail()
         };
         i++;
     }
    DefaultTableModel tabelaClientes = new DefaultTableModel(dados,colunas);
    tabela.setModel(tabelaClientes);
 }
    
 public void  atualizarTabelaClientes() {
    
    ClienteDAO dao = new ClienteDAO();
    List<Clientes> listar = dao.listar("");
     DefaultTableModel model = (DefaultTableModel) tabela.getModel();
    
    System.out.println("Total de clientes: " + listar.size()); // Depuração
    
    for (Clientes c : listar) {
        model.addRow(new Object[] {
            c.getId(),
            c.getNome(),
            c.getCpf(),
            c.getCelular(),
            c.getEmail()
        });
    }
}

    
    /**
     * Função que preencher a tabela com base no nome pesquisado
     */
    public void PreencherTabelaNome(String nome) {
        try {
            ClienteDAO dao = new ClienteDAO();
            List<Clientes> listar = dao.listar(nome);
            System.out.println("Total de clientes: " + listar.size()); // Adicione isso para depuração

            if (nome.equals("")) {
                JOptionPane.showMessageDialog(null, "Escreva um nome para pesquisar");
                return; // Retorna se a lista estiver vazia
            }
            if (listar == null || listar.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nenhum cliente encontrado com o nome: " + nome);
                return; // Retorna se a lista estiver vazia
            }

            preencherTabela(listar);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar clientes: " + e.getMessage());
        }
    }

    /*
    * Função para limpar a tabela quando algum objeto é editado ou excluido
    */
    public void limparTabela() {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        if (model.getRowCount() > 0) { // Evita erro se a tabela já estiver vazia
            model.setRowCount(0);
        } 
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btaEditar = new javax.swing.JButton();
        btaExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Clientes");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Lista de Clientes");

        txtNome.setBackground(new java.awt.Color(255, 255, 255));

        btnPesquisar.setBackground(new java.awt.Color(255, 153, 102));
        btnPesquisar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(0, 0, 0));
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btaEditar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btaEditar.setText("Editar");
        btaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaEditarActionPerformed(evt);
            }
        });

        btaExcluir.setBackground(new java.awt.Color(255, 0, 0));
        btaExcluir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btaExcluir.setForeground(new java.awt.Color(0, 0, 0));
        btaExcluir.setText("Excluir");
        btaExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaExcluirActionPerformed(evt);
            }
        });

        tabela.setBackground(new java.awt.Color(255, 255, 255));
        tabela.setForeground(new java.awt.Color(0, 0, 0));
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(btaExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar)
                    .addComponent(btaEditar)
                    .addComponent(btaExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        String nomePesquisa = txtNome.getText();

        if (!nomePesquisa.isEmpty()) {
            PreencherTabelaNome(nomePesquisa);

        } else {
            ClienteDAO dao = new ClienteDAO();
            List<Clientes> clientes = dao.listar("");
            preencherTabela(clientes);

        }

        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btaExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaExcluirActionPerformed
        int selectLinha = tabela.getSelectedRow();

// Verificar se alguma linha foi selecionada
        if (selectLinha != 1) {
            String idClientes = (String) tabela.getValueAt(selectLinha, 0);
            int id = Integer.parseInt(idClientes); // Converte String do id para INT

            ClienteDAO dao = new ClienteDAO();
            Clientes clientes = dao.buscarPorId(id);

            if (clientes != null) {
                // Exclui o cliente do banco de dados
                dao.excluirClientes(clientes);
                limparTabela();
                atualizarTabelaClientes();

                JOptionPane.showMessageDialog(this, "Cliente excluído com sucesso!");

            } else {
                JOptionPane.showMessageDialog(this, "Erro ao buscar o cliente.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Mensagem de erro caso nenhuma linha esteja selecionada
            JOptionPane.showMessageDialog(this, "Nenhuma linha selecionada.", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btaExcluirActionPerformed

    private void btaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaEditarActionPerformed
        int selectLinha = tabela.getSelectedRow();
        if (selectLinha != -1) {
            DefaultTableModel modeloTabela = (DefaultTableModel) tabela.getModel();

            String idClientes = (String) tabela.getValueAt(selectLinha, 0);
            int id = Integer.parseInt(idClientes); // Converte String do id para INT

            ClienteDAO dao = new ClienteDAO();
            Clientes clienteExiste = dao.buscarPorId(id);

            if (clienteExiste != null) {
                telaEditarCliente telaEditar = new telaEditarCliente(id);
                telaEditar.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao buscar o cliente.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nenhuma linha selecionada.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btaEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaListaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btaEditar;
    private javax.swing.JButton btaExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
