/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.aluguel.ferramentasaluguel.view;

import br.com.aluguel.ferramentasaluguel.dao.ClienteDAO;
import br.com.aluguel.ferramentasaluguel.dao.FerramentaDAO;
import br.com.aluguel.ferramentasaluguel.dao.ReservasDAO;
import br.com.aluguel.ferramentasaluguel.model.Clientes;
import br.com.aluguel.ferramentasaluguel.model.Ferramentas;
import br.com.aluguel.ferramentasaluguel.model.Reservas;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danie
 */
public class telaAddReservas extends javax.swing.JFrame {

    //crio uma "variavel" para Jlist
     String[] colunas = {"Nome", "Preço diária"};
     DefaultTableModel tabelaFerramentaSEL = new DefaultTableModel(colunas, 0);
     private double somaTotal = 0; // Inicializa a soma total
        
   
    public telaAddReservas() {
        initComponents();
        preencherComboBox();
        setLocationRelativeTo(null);
    }
    
    
 /**
     * Preenche o combobox com a lista de produtores de podcasts.
     */
    private void preencherComboBox() {
        FerramentaDAO dao = new FerramentaDAO();

        comboBox.removeAllItems();

        List<Ferramentas> lista = dao.listar("");

        for (Ferramentas f : lista) {
            if(f.isDisponivel() == true) {
                comboBox.addItem(f);
            }
        }

        comboBox.setSelectedIndex(-1); // Deixa a seleção vazia inicialmente
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btaHome = new javax.swing.JButton();
        btaAddCliente = new javax.swing.JButton();
        btaAddFerramenta = new javax.swing.JButton();
        btaVenda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btaUsuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox<>();
        btaAdicionar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        valorTotal = new javax.swing.JLabel();
        btaFinalizarCompra = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dataLocacao = new javax.swing.JFormattedTextField();
        dataPrevisao = new javax.swing.JFormattedTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vendas");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.setForeground(new java.awt.Color(255, 153, 51));

        btaHome.setBackground(new java.awt.Color(255, 153, 51));
        btaHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-casa-50.png"))); // NOI18N
        btaHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaHomeActionPerformed(evt);
            }
        });

        btaAddCliente.setBackground(new java.awt.Color(255, 153, 51));
        btaAddCliente.setForeground(new java.awt.Color(255, 153, 51));
        btaAddCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-adicionar-usuário-masculino-50.png"))); // NOI18N
        btaAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaAddClienteActionPerformed(evt);
            }
        });

        btaAddFerramenta.setBackground(new java.awt.Color(255, 153, 51));
        btaAddFerramenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-ferramenta-50.png"))); // NOI18N
        btaAddFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaAddFerramentaActionPerformed(evt);
            }
        });

        btaVenda.setBackground(new java.awt.Color(255, 153, 51));
        btaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-adicionar-o-carrinho-de-compras-50.png"))); // NOI18N
        btaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaVendaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Olá,");

        btaUsuario.setBackground(new java.awt.Color(255, 153, 51));
        btaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-usuário-50.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btaHome, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btaAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btaAddFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btaVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btaVenda, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btaHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btaAddCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btaAddFerramenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CPF do Cliente:");

        txtCPF.setBackground(new java.awt.Color(255, 255, 255));
        txtCPF.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Selecionar as ferrametas:");

        comboBox.setBackground(new java.awt.Color(255, 255, 255));
        comboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboBox.setForeground(new java.awt.Color(0, 0, 0));
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        btaAdicionar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btaAdicionar.setForeground(new java.awt.Color(0, 0, 0));
        btaAdicionar.setText("Adicionar");
        btaAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaAdicionarActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Total R$");

        valorTotal.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        valorTotal.setForeground(new java.awt.Color(0, 51, 0));
        valorTotal.setText("0.00");

        btaFinalizarCompra.setBackground(new java.awt.Color(102, 255, 51));
        btaFinalizarCompra.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btaFinalizarCompra.setForeground(new java.awt.Color(0, 0, 0));
        btaFinalizarCompra.setText("Finalizar");
        btaFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaFinalizarCompraActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Data locação:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Data prevista da devolução:");

        dataLocacao.setBackground(new java.awt.Color(255, 255, 255));
        dataLocacao.setForeground(new java.awt.Color(0, 0, 0));
        try {
            dataLocacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        dataPrevisao.setBackground(new java.awt.Color(255, 255, 255));
        dataPrevisao.setForeground(new java.awt.Color(0, 0, 0));
        try {
            dataPrevisao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tabela.setBackground(new java.awt.Color(255, 255, 255));
        tabela.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabela.setForeground(new java.awt.Color(0, 0, 0));
        tabela.setModel(tabelaFerramentaSEL);
        jScrollPane3.setViewportView(tabela);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(txtCPF)
                            .addComponent(jLabel3)
                            .addComponent(comboBox, 0, 196, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btaAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataPrevisao, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(132, 132, 132))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addComponent(valorTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btaFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataPrevisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btaAdicionar))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(valorTotal)
                            .addComponent(btaFinalizarCompra)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(dataLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btaHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaHomeActionPerformed
        telahome telahome = new telahome();
        telahome.setVisible(true);
        dispose();
    }//GEN-LAST:event_btaHomeActionPerformed

    private void btaAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaAddClienteActionPerformed
        telaaddcliente addcliente = new telaaddcliente();
        addcliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_btaAddClienteActionPerformed

    private void btaAddFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaAddFerramentaActionPerformed
        telaAddFerramentas telaFerramentas = new telaAddFerramentas();
        telaFerramentas.setVisible(true);
        dispose();
    }//GEN-LAST:event_btaAddFerramentaActionPerformed

    private void btaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btaVendaActionPerformed

    private void atualizarValorTotal(double total) {
        valorTotal.setText(String.valueOf(total));
    }
    
    
    private void btaAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaAdicionarActionPerformed
  
 //preenche a tabela com ferramentas      
        FerramentaDAO dao = new FerramentaDAO();
        Ferramentas ferramentaSelecionada = (Ferramentas) comboBox.getSelectedItem();
        String produtorSEL = ferramentaSelecionada != null ? ferramentaSelecionada.getNome() : "";

        List<Ferramentas> ferra = dao.listar(produtorSEL);    


// Verifica se já existe na tabela
        boolean ferramentaExiste = false;
        for (int i = 0; i < tabelaFerramentaSEL.getRowCount(); i++) {
            String nomeExistente = tabelaFerramentaSEL.getValueAt(i, 0).toString(); // Obtém o nome da coluna 0
            if (nomeExistente.equals(produtorSEL)) {
                ferramentaExiste = true;
                break; // Sai do loop pois já encontrou
            }
        }

// Se não existe, adiciona
        if (!ferramentaExiste) {
            for (Ferramentas f : ferra) {
                if (f.getNome().equals(produtorSEL)) {
                    Object[] obj = {
                        f.getNome(), 
                        f.getPreco_diaria()
                    };
                    tabelaFerramentaSEL.addRow(obj);

                    // Adiciona o valor da ferramenta à soma total
                    double valorFerramenta = f.getPreco_diaria();                    
                    somaTotal += valorFerramenta; // Soma o valor da ferramenta
                }
            }
        }
        
        
        atualizarValorTotal(somaTotal);
        

    }//GEN-LAST:event_btaAdicionarActionPerformed

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed

    }//GEN-LAST:event_comboBoxActionPerformed

    private void btaFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaFinalizarCompraActionPerformed
// Coleta os dados para a venda
        double valorTotal = somaTotal;
        String cpfCliente = txtCPF.getText();

// Validação do CPF
        if (!cpfCliente.matches("\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}")) {
            JOptionPane.showMessageDialog(null, "CPF inválido! Use o formato XXX.XXX.XXX-XX.");
            return;
        }

// Validação da data antes da conversão
        if (!dataLocacao.getText().matches("\\d{2}/\\d{2}/\\d{4}") || !dataPrevisao.getText().matches("\\d{2}/\\d{2}/\\d{4}")) {
            JOptionPane.showMessageDialog(null, "Data inválida! Use o formato DD/MM/AAAA.");
            return;
        }

// Conversão da string para LocalDate
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate dateLocacao = LocalDate.parse(dataLocacao.getText(), formatter);
        LocalDate datePrevisao = LocalDate.parse(dataPrevisao.getText(), formatter);

FerramentaDAO ferramentasDAO = new FerramentaDAO(); // Criar um DAO para manipular ferramentas

List<Ferramentas> listFerramentas = new ArrayList<>();
for (int i = 0; i < tabelaFerramentaSEL.getRowCount(); i++) {
    String nomeFerramenta = tabelaFerramentaSEL.getValueAt(i, 0).toString();
    double precoFerramenta = Double.parseDouble(tabelaFerramentaSEL.getValueAt(i, 1).toString());

    // Busca no banco antes de criar uma nova
    Ferramentas ferramenta = ferramentasDAO.buscarPorNome(nomeFerramenta);
    if (ferramenta == null) {
        ferramenta = new Ferramentas();
        ferramenta.setNome(nomeFerramenta);
        ferramenta.setPreco_diaria(precoFerramenta);

        ferramenta = ferramentasDAO.salvar(ferramenta); // Persistir no banco
    }

    listFerramentas.add(ferramenta);
}


// Verifica se há ferramentas na lista
        if (listFerramentas.isEmpty()) {
            JOptionPane.showMessageDialog(null, "A lista de ferramentas não pode estar vazia!");
            return;
        }

// Busca o cliente pelo CPF
// Criando objeto Cliente e associando à reserva
        ClienteDAO dao = new ClienteDAO();
        Clientes clientes = new Clientes();    
        int RetornarID = dao.getIdClientePorCPF(cpfCliente);
        clientes.setId(RetornarID );
        

// Verifica se o cliente foi encontrado
        if (clientes == null) {
            JOptionPane.showMessageDialog(null, "Cliente não encontrado");
            return;
        }

// Criação do objeto de reserva e salvamento no banco
        Reservas reservas = new Reservas();
        reservas.setCliente(clientes);
        reservas.setData_locacao(dateLocacao);
        reservas.setData_prevista(datePrevisao);
        reservas.setFerramentas(listFerramentas);
        reservas.setPreco_total(valorTotal);

        ReservasDAO reservasdao = new ReservasDAO();
        reservasdao.cadastrarReserva(reservas);

// Limpa os campos da tela
        txtCPF.setText("");
        dataLocacao.setText("");
        dataPrevisao.setText("");
        comboBox.setSelectedIndex(-1);
        tabelaFerramentaSEL.setRowCount(0);

    }//GEN-LAST:event_btaFinalizarCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaAddReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaAddReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaAddReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaAddReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaAddReservas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btaAddCliente;
    private javax.swing.JButton btaAddFerramenta;
    private javax.swing.JButton btaAdicionar;
    private javax.swing.JButton btaFinalizarCompra;
    private javax.swing.JButton btaHome;
    private javax.swing.JButton btaUsuario;
    private javax.swing.JButton btaVenda;
    private javax.swing.JComboBox<Ferramentas> comboBox;
    private javax.swing.JFormattedTextField dataLocacao;
    private javax.swing.JFormattedTextField dataPrevisao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabela;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JLabel valorTotal;
    // End of variables declaration//GEN-END:variables
}
